# Site settings
title: CoyIM
email: coyim@thoughtworks.com
description: > # this means to ignore newlines until "baseurl:"
    CoyIM is a safe and secure chat client.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://coy.im"

version: 0.3.8
date: 08 Jun 2017

# Build settings
markdown: kramdown
